### ISSUE TITLE
If you delete an image the program will keep overwriting one random image

### ISSUE THREAD

**Issue by AdrianSima** [Blokatt/GM48TT#1]
If you delete an image that is not the last one in the folder the program will start overwriting one of the images over and over again.
I can't figure out how it chooses what image to overwrite, because it is not always overwriting the last one.

I've been using version 1.0.2 on Windows 10 Pro with latest updates.

**Comment by odditica** [comment]
Thanks for the heads up, will try to fix it and upload a new binary ASAP.

**Comment by odditica** [comment]
The problem has been fixed, please download the latest release [here](https://github.com/Blokatt/GM48TT/releases/tag/1.0.3).
